title: Defenders of Wildlife - Group 1
description: Creating a Better User Experience
baseurl: "" # the subpath of your site, e.g. /blog
url: "projectdow.tk" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Group One
author-image:   wolf.jpg
author-job:     Defenders of Wildlife
author-email:   bdubon@terpmail.umd.edu # Add your email for contant form.
author-twitter: defendersofwildlife # Add your twitter account
about-author:   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Blandit aliquam etiam erat velit scelerisque. Purus semper eget duis at tellus at urna. Donec et odio pellentesque diam. Quis hendrerit dolor magna eget est lorem ipsum dolor. Nunc pulvinar sapien et ligula ullamcorper. Ullamcorper dignissim cras tincidunt lobortis feugiat. Sed arcu non odio euismod lacinia. Sed cras ornare arcu dui vivamus arcu felis bibendum ut.

# Social settings
social-twitter: defenders 
social-facebook: defendersofwildlife
social-github:    
social-pinterest: 
social-instagram: defendersofwildlife
social-youtube: defendersofwildlife
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: G1-DoW # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
