title: Defenders of Wildlife - Group 1
description: Creating a Better User Experience
baseurl: "https://bdubon.github.io/DoW" # the subpath of your site, e.g. /blog
url: "http://bdubon.github.io/DoW/" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Group One
author-image:   wolf.jpg
author-job:     InfoSci Students
author-email:   bdubon@umd.edu # Add your email for contant form.
author-twitter: defendersofwildlife # Add your twitter account
about-author:   Creating a Better User Experience.

# Social settings
social-twitter: defenders 
social-facebook: defendersofwildlife
social-github:    
social-pinterest: 
social-instagram: defendersofwildlife
social-youtube: defendersofwildlife
social-vk:   
social-linkedin:

# Comment Section (Disqus)
disqus-identifier: G-DoW # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
